# Generated by Django 6.0.4 on 2026-04-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("id_number", models.CharField(max_length=100, unique=True)),
                ("rate", models.FloatField()),
                ("overtime_pay", models.FloatField(blank=True, null=True)),
                ("allowance", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=50)),
                ("date_range", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=10)),
                ("pay_cycle", models.IntegerField()),
                ("rate", models.FloatField()),
                ("earnings_allowance", models.FloatField()),
                ("deductions_tax", models.FloatField()),
                ("deductions_health", models.FloatField()),
                ("pag_ibig", models.FloatField()),
                ("sss", models.FloatField()),
                ("overtime", models.FloatField()),
                ("total_pay", models.FloatField()),
                (
                    "id_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="payroll_app.employee",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
    ]
